openapi: '3.0.0'

info:
  title: 'angular-spring-oauth2-example'
  version: '1.0.0'

paths:

  /session-token:

    get:
      operationId: loginOrRefresh
      summary: |
        login and token-refresh endpoint
      tags:
        - 'Session'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: |
            body contains fresh session token, encoded
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: |
            user needs to authenticate

    delete:
      operationId: logout
      summary: |
        termination endpoint, invalidates the session for the given token
      tags:
        - 'Session'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 'the presented session was ended'

  /auth-providers:

    get:
      operationId: getAuthProviders
      summary: |
        get a specific organisation record
      tags:
        - 'Session'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 'organisation details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvidersDoc'

components:

  securitySchemes:

    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    ProvidersDoc:
      type: object
      properties:
        providers:
          type: array
          items:
            $ref: '#/components/schemas/ProviderDoc'
      required:
        - providers

    ProviderDoc:
      type: object
      properties:
        shortName: { type: string }
        loginUrl: { type: string }
      required:
        - workEmail
        - worksFor
